version: '3'
services:
  postgres:
    image: postgres
    container_name: portfolio_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: portfolio_postgres
    command: postgres
    restart: always

  redis:
    image: redis
    container_name: portfolio_redis
    ports:
      - '6379:6379'
    # restart: always
